= arjunsatarkar.net

This is the source repository for Arjun Satarkar's personal website.

== www

This is an HTTP server intended to be mapped by a reverse proxy to www.arjunsatarkar.net.
It can be run in a container (eg. Podman, Docker) or without.

Prerequisites:

Must always be installed:

* https://just.systems/[just]

Need not be explicitly installed for containerized usage:

* https://asciidoctor.org/[Asciidoctor]
* https://www.python.org/[Python 3]
* https://bottlepy.org/[Bottle]
* https://www.gevent.org/[Gevent]

Must only be installed for containerized usage:

* https://podman.io/[Podman]
** or compatible equivalent like https://docker.com/[Docker], but alias it `podman` or some adjustment will be needed

=== Uncontainerized operation

To build: run `+just+` in the `+www/+` directory.

To run: run `+www/serve.py+`. If an argument is passed, it will be interpreted as the port to listen on (default 27701).

After changing something in `+www/sitesrc+`, perform the build step again to update the served site.

=== Containerized operation

To build: run `+just build-image+` in the `+www+` directory.

To run: run `+just run-container+` in the `+www+` directory.

After changing something in `+www/sitesrc+`, run `+www/trigger_rebuild.sh+` to update the served site.

