= arjunsatarkar.net

This is the source repository for Arjun Satarkar's personal website.

== www

This is an HTTP server intended to be mapped by a reverse proxy to www.arjunsatarkar.net.
It can be run in a container (eg. Podman, Docker) or without.

Prerequisites:

* https://just.systems/[just]
* https://asciidoctor.org/[Asciidoctor] (not necessary if containerized)
* https://www.python.org/[Python 3] (not necessary if containerized)
* https://bottlepy.org/[Bottle] (not necessary if containerized)
* https://podman.io/[Podman] (only necessary if containerized)

=== Uncontainerized operation

To build: run `+just+` in the `+www/+` directory.

To run: run `+www/serve.py+`. If an argument is passed, it will be interpreted as the port to listen on (default 27701).

After changing something in `+www/sitesrc+`, perform the build step again to update the served site.

=== Containerized operation

To build: run `+just build-image+` in the `+www+` directory.

To run: run `+just run-container+` in the `+www+` directory.

After changing something in `+www/sitesrc+`, run `+www/trigger_rebuild.sh+` to update the served site.

