# syntax=docker/dockerfile:1

FROM docker.io/python:3.11-alpine3.17

RUN apk add just asciidoctor python3
RUN pip3 install bottle

WORKDIR /site
COPY . .

RUN just

CMD ["python3", "serve.py"]
EXPOSE 80
