FROM docker.io/python:3.11-alpine3.17

RUN apk add just asciidoctor
RUN pip3 install bottle gevent

WORKDIR /site
COPY . .

RUN just
# We will mount it from outside so we can update from outside
RUN rm -rf sitesrc

CMD ["python3", "serve.py"]
EXPOSE 27701
