build-site:
	asciidoctor -a webfonts! -a last-update-label! -a stylesheet=main.css -a stylesdir=styles -a linkcss -a copycss=../styles/main.css -a docinfo=shared-head,shared-header -a docinfodir=docinfo -D webroot contentsrc/*.adoc
	asciidoctor -a webfonts! -a last-update-label! -a stylesheet=main.css -a stylesdir=styles -a linkcss -a copycss=../styles/main.css -a docinfo=shared-head -a docinfodir=docinfo -D webroot contentsrc/index.adoc
	cp -f contentsrc/favicon.svg contentsrc/cc_by_4-0.txt webroot/

build-image:
	podman build -t www.arjunsatarkar.net .	

run-image:
	podman run --name www.arjunsatarkar.net -dp 127.0.0.1:27701:80 -v ./contentsrc:/site/contentsrc www.arjunsatarkar.net
