FROM docker.io/nginx:1.23-alpine

RUN apk add cgit git fcgiwrap python3 asciidoctor highlight
RUN rm /etc/nginx/conf.d/*

COPY nginx.conf /etc/nginx/conf.d/scm.arjunsatarkar.net.conf
COPY cgitrc /etc/cgitrc
COPY syntax_highlighting.py /
COPY adoc_about_formatter.py /
COPY entrypoint.sh /
COPY header.html /

ENTRYPOINT /entrypoint.sh
